### ISSUE TITLE
Bad PDF?

### ISSUE THREAD

**Issue by WA2FZW** [WA2FZW/A-DIY-Controller-for-the-SPID-Rotators-by-WA2FZW#1]
For some reason, when I try to view the PDF document on Github, it says bad file format, however when I download it, it opens just fine.

**Comment by joshuajayg** [comment]
PDF works fine for me in Github.  Using Firefox on a Macbook.

**Comment by WA2FZW** [comment]
Upon further investigation, this seems to be a problem on only on one of my computers. I get an error when I try to read the PDF using Chrome, but it works fine using WIndows (7) Explorer or when I download the file it opens fine with Adobe.

Consider the issue closed!
